---
files: ^(.*\.(py|json|md|sh|yaml|cfg|txt))$
exclude: ^(\.[^/]*cache/.*|.*/_user.py)$
repos:
  - repo: https://github.com/executablebooks/mdformat
    # Do this before other tools "fixing" the line endings
    rev: 0.7.17
    hooks:
      - id: mdformat
        name: Format Markdown
        entry: mdformat  # Executable to run, with fixed options
        language: python
        types: [markdown]
        args: [--wrap, '78', --number]
        additional_dependencies:
          - mdformat-toc
          - mdformat-beautysh
          # -mdformat-shfmt
          # -mdformat-tables
          - mdformat-config
          - mdformat-black
          - mdformat-web
          - mdformat-gfm
          - setuptools
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: no-commit-to-branch
        args: [--branch, main]
      - id: check-yaml
        args: [--unsafe]
      - id: debug-statements
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-json
      - id: mixed-line-ending
      - id: check-builtin-literals
      - id: check-ast
      - id: check-merge-conflict
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
      - id: check-docstring-first
      - id: fix-byte-order-marker
      - id: check-case-conflict
      # - id: check-toml
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.33.0
    hooks:
      - id: yamllint
        args:
          - --no-warnings
          - -d
          - '{extends: relaxed, rules: {line-length: {max: 90}}}'
  - repo: https://github.com/lovesegfault/beautysh.git
    rev: v6.2.1
    hooks:
      - id: beautysh
        additional_dependencies:
          - setuptools
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.15.0
    hooks:
      - id: pyupgrade
#  - repo: https://github.com/psf/black
#    rev: 22.6.0
#    hooks:
#      - id: black
#  - repo: https://github.com/Lucas-C/pre-commit-hooks-bandit
#    rev: v1.0.6
#    hooks:
#      - id: python-bandit-vulnerability-check
#        args: [--skip, 'B101,B311', --recursive, .]
#
#  - repo: https://github.com/fsouza/autoflake8
#    rev: v0.3.2
#    hooks:
#      - id: autoflake8
#        args:
#          - -i
#          - -r
#          - --expand-star-imports
#          - .
#  - repo: https://github.com/PyCQA/flake8
#    rev: 4.0.1
#    hooks:
#      - id: flake8
#        additional_dependencies:
#          - pyproject-flake8==0.0.1a2
#          - flake8-bugbear==22.1.11
#          - flake8-comprehensions==3.8.0
#          - flake8_2020==1.6.1
#          - mccabe==0.6.1
#          - pycodestyle==2.8.0
#          - pyflakes==2.4.0
#  - repo: https://github.com/PyCQA/isort
#    rev: 5.10.1
#    hooks:
#      - id: isort
  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.6
    hooks:
      - id: codespell
        args:
          # - --builtin=clear,rare,informal,usage,code,names,en-GB_to_en-US
          - --builtin=clear,rare,informal,usage,code,names
          - --ignore-words-list=hass,master
          - --skip="./.*"
          - --quiet-level=2
#  - repo: https://github.com/pylint-dev/pylint
#    rev: v3.0.3
#    hooks:
#      - id: pylint
#        args:
#          - --reports=no
#          - --py-version=3.7
#        #exclude: ^$
#  - repo: https://github.com/pre-commit/mirrors-mypy
#    rev: v0.961
#    hooks:
#      - id: mypy
#        args:
#          - --ignore-missing-imports
#          - --install-types
#          - --non-interactive
#          - --check-untyped-defs
#          - --show-error-codes
#          - --show-error-context
#        additional_dependencies:
#          - zigpy==0.43.0
