name: Regression tests

on:
  push:
    paths:
     - '**.py'
     - 'tests/**'
     - '.github/workflows/pythonapp.yml'
  pull_request:
    paths:
     - '**.py'
     - 'tests/**'
     - '.github/workflows/pythonapp.yml'

jobs:
  test:
    runs-on: ubuntu-latest
    container: setsoft/kicad_auto_test:ki9

    steps:
    - uses: actions/checkout@v3
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings.
        flake8 . --count --exit-zero --statistics
    - name: Test KiCad 7
      shell: bash
      run: |
        make test_server
    - name: Store results
      if: ${{ always() }}
      uses: actions/upload-artifact@v4
      with:
        name: Test_Output_ki6
        path: output
